Feature/contacts section
voyageglobal/voyage-frontend pull request #6
Opened 2024-05-31 13:10 UTC by min-in-zon

2024-06-03 10:29 UTC, adadychanka requested changes

2024-06-03 10:29 UTC, adadychanka commented on src/components/common/icons/Facebook.jsx
> +const FacebookIcon = () => {
https://www.freecodecamp.org/news/how-to-import-svgs-in-react-and-vite/

Let's use 6th approach to handle svgs

2024-06-03 10:29 UTC, adadychanka commented on src/pages/MainPage/ContactsSection.jsx
> +import instaIcon from '../../assets/img/instaIcon.svg';
Why don't you update other icons as well?

2024-06-03 10:29 UTC, adadychanka commented on src/pages/MainPage/ContactsSection.jsx
> +              <button type="submit">Send Message</button>
Are you going to implement email-sending functionality in the PR or the following one?

2024-06-03 10:29 UTC, adadychanka commented on src/pages/MainPage/contactsSection.scss
> +        form {
it's not really a good practice to stick to tags in styles, it's better to create class names for that

2024-06-05 16:05 UTC, min-in-zon commented on src/pages/MainPage/ContactsSection.jsx
> +              <button type="submit">Send Message</button>
I'm going to add all the functionality after creating all html and switching it to tailwind.сss

2024-06-05 17:00 UTC, adadychanka approved these changes

2024-06-05 17:01 UTC, merged